### ISSUE TITLE
null safe versions of logging and test packages fail the version solver.

### ISSUE THREAD

**Issue by wstrange** [dart-lang/core#459]
I can't seem to find a pubspec combination that satisfies the solver for logging and test:

```
name: test_null
description: A sample command-line application.

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  logging: "^1.0.0-nullsafety"

dev_dependencies:
  test: ^1.16.0-nullsafety

```
