### ISSUE TITLE
consider adding an example dir (for more pub points) 

### ISSUE THREAD

**Issue by pq** [dart-lang/core#746]
Follow-up from https://github.com/dart-lang/core/issues/745

@isoos adds:

> Any of these should do:
> - example/README.md
> - example/lints.dart
> - example/example.dart
> - or [more](https://github.com/dart-lang/pana/blob/102dc26186866b02c0b8b09cffc70984231f639e/lib/src/maintenance.dart#L20-L34)

How about:

example/README.md

> An example project that uses Dart recommended lints.

example/analysis_options.yaml

```yaml
include: package:lints/recommended.yaml
```

example/pubspec.yaml

```yaml
name: example
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
   lints: ^1.0.0
```
