### ISSUE TITLE
non_constant_identifier_names is invalid in `analysis_options.yaml`

### ISSUE THREAD

**Issue by medz** [dart-lang/core#795]
I am using the following rules in `analysis_options.yaml`
```yaml
include: package:lints/recommended.yaml
linter:
   rules:
     - non_constant_identifier_names
```

The editor and analyze still throw:
```
The variable name 'xxx' isn't a lowerCamelCase identifier.
Try changing the name to follow the lower CamelCase style.
```

my code:

```dart
void _$$_Test() {}
```

<img width="929" alt="image" src="https://user-images.githubusercontent.com/5564821/224902509-46f54e8c-0242-439d-b772-32c1a7270f88.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/5564821/224902699-d60f58f6-5667-483e-9873-d88197dc529a.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/5564821/224902782-5988f1db-41f6-4614-a3d7-7790e6f34a0c.png">
<img width="670" alt="image" src="https://user-images.githubusercontent.com/5564821/224902828-c69e522a-73fb-4aa9-9e05-28f6931bdb05.png">
